trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm run build
      displayName: 'npm build'

    - task: TfxInstaller@2
      inputs:
        version: 'v0.6.x'

    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: 
        outputPath: '$(Build.ArtifactStagingDirectory)/Extension'
        updateTasksVersion: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Extension'
        ArtifactName: 'extension'
        publishLocation: 'Container'