# Node.js with gulp
# Build a Node.js application using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    gulp package --gulpfile gulpfile.js
  displayName: 'npm install and run gulp'
